### shape(R,)和shape(R,1)的区别
可以参考[这个文章](https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r)
将1维向量二维化,首先要清楚它column还是row,添加一个None的维度即可完成转化.
```python
    column = column[:,None];
    row = row[None,:]
```

### 切片

In [1]:
#切片是满足 左闭，右开
a=[1,2,3,4]
print(a[::1]);
print(a[::-1]);
print(a[:]);
print(a[:-1]);
print(a[:-2]);

[1, 2, 3, 4]
[4, 3, 2, 1]
[1, 2, 3, 4]
[1, 2, 3]
[1, 2]


### numpy行向量列向量之间转换

In [2]:
import numpy as np;
# np没有一维向量,只有(4)
a=np.array([1,2,3,4]);
print('a:',a,'a.shape',a.shape)

#转变成 (1,4)
aa=np.array([a])
print('aa:',aa,'aa.shape',aa.shape)

#转变成(4,1)
aa=np.array([a]).T
print('aa:\n',aa,'\naa.shape',aa.shape)

# 用reshape
b=a.reshape(-1,1);
print('row into column vec:\n',b,'\nb.shape',b.shape)
#列向量变行向量 reshape
c=b.reshape(1,-1);
print('column into row vec:',c,'c.shape',c.shape)

a: [1 2 3 4] a.shape (4,)
aa: [[1 2 3 4]] aa.shape (1, 4)
aa:
 [[1]
 [2]
 [3]
 [4]] 
aa.shape (4, 1)
row into column vec:
 [[1]
 [2]
 [3]
 [4]] 
b.shape (4, 1)
column into row vec: [[1 2 3 4]] c.shape (1, 4)


### 倒序循环

In [3]:
for i in range(10-1,-1,-1):
    print(i);

9
8
7
6
5
4
3
2
1
0


###  行，列，全体求和

In [4]:
A=np.ones([3,3]);
np.sum(A)

9.0

In [5]:
np.sum(A[:,1])

3.0

In [6]:
np.sum(A[1,:])

3.0

In [7]:
A=np.array([[1,2,3,4],[5,6,7,8]]);
print('A=\n',A);

#然后对A的每一列除以sum的值 ，相当于列的概率分布
# none的作用还是初始化1维向量
Sum = np.sum(A,axis=0)
print('Sum row together\n',Sum);
print('Sum[None,:]\n',Sum[None,:])
print('Sum[None,:] shape\n',Sum[None,:].shape)
print('Matrix divide row-vector:\n', A / Sum[None,:]);


Sum=np.sum(A,axis=1);
print('Sum column together\n',Sum);
print('Matrix divide column-vector:\n',A / Sum[:,None]);

A=
 [[1 2 3 4]
 [5 6 7 8]]
Sum row together
 [ 6  8 10 12]
Sum[None,:]
 [[ 6  8 10 12]]
Sum[None,:] shape
 (1, 4)
Matrix divide row-vector:
 [[0.16666667 0.25       0.3        0.33333333]
 [0.83333333 0.75       0.7        0.66666667]]
Sum column together
 [10 26]
Matrix divide column-vector:
 [[0.1        0.2        0.3        0.4       ]
 [0.19230769 0.23076923 0.26923077 0.30769231]]


### 最后一个元素用a[-1]来寻找 ,类似matlab a(end)

In [8]:
a1=np.array([1,2,3])
a1[-1]

3

In [9]:
a1[-2]

2

In [10]:
a1[-3]

1

In [11]:
a1[::-1]

array([3, 2, 1])

### 矩阵连续点乘

In [12]:
size = [3,3]
A=np.random.rand(3,3);
B= A+1;
C =A /2 ;
D = A -10;

ans=A.dot(B).dot(C).dot(D)
print(ans)
print('------')
from functools import reduce ;
ans = reduce(np.dot,[A,B,C,D]);
print(ans)


[[-20.70706468 -20.03823875 -20.71078327]
 [-22.92167992 -22.11471662 -22.87573685]
 [-45.66675896 -44.07686786 -45.58749156]]
------
[[-20.70706468 -20.03823875 -20.71078327]
 [-22.92167992 -22.11471662 -22.87573685]
 [-45.66675896 -44.07686786 -45.58749156]]


### 矩阵的多维性质

In [13]:
A=np.random.randint(1,10,[3,3,3],dtype=np.int64)
A

array([[[8, 8, 2],
        [1, 5, 9],
        [1, 4, 3]],

       [[1, 7, 7],
        [5, 5, 2],
        [6, 9, 6]],

       [[8, 4, 4],
        [2, 5, 3],
        [8, 5, 7]]])

In [14]:
np.sum(A,axis=0)

array([[17, 19, 13],
       [ 8, 15, 14],
       [15, 18, 16]])

In [15]:
#沿axis同于1的方向做加法 等价于3x3中的行的方向
np.sum(A,axis=1)

array([[10, 17, 14],
       [12, 21, 15],
       [18, 14, 14]])

In [16]:
np.sum(A,axis=2)

array([[18, 15,  8],
       [15, 12, 21],
       [16, 10, 20]])

In [17]:
# 所有3x3的[0,0]位置组成新的向量
A[:,0,0]

array([8, 1, 8])

In [18]:
# 第1个的 3x3（从第0个开始）
A[1,]
#等价A[1,:,:], 后面如果有冒号，可以省略

array([[1, 7, 7],
       [5, 5, 2],
       [6, 9, 6]])

In [19]:
A[:,1,:]
# 从后面开始，后面两个维度[1,:]代表3x3矩阵的第1行，再往前看:,代表所有3x3矩阵的第1行

array([[1, 5, 9],
       [5, 5, 2],
       [2, 5, 3]])

### empty初始化

In [20]:
A=np.empty(A.shape);
print(A)

[[[ 6.89825974e-310  6.89825974e-310 -5.53762849e+047]
  [ 6.89825622e-310  6.89825025e-310 -2.01932978e-197]
  [ 6.89825685e-310  6.89825025e-310 -1.89909690e+039]]

 [[ 6.89825918e-310  6.89825025e-310  3.90827786e-120]
  [ 6.89825028e-310  6.89825025e-310  4.87911512e-057]
  [ 6.89825027e-310  6.89825025e-310 -3.69093313e-023]]

 [[ 6.89825025e-310  6.89825025e-310  3.54328388e-112]
  [ 6.89825905e-310  6.89825025e-310 -7.71995083e-296]
  [ 6.89826067e-310  6.89825025e-310  1.34385856e-321]]]


In [21]:
np.random.randn(2,2)

array([[ 0.58726406,  1.68250273],
       [ 0.15645254, -0.17207964]])

### 判断矩阵的每一行，与另外一个向量是否相等，得到真值矩阵

In [22]:
A=np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2]]);
vec = np.array([0,2,1,2]);
np.where(A ==vec,1,0)

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1]])

### tile用法

### stack

In [2]:
import numpy as np

In [3]:
a=np.array([1,2,3])

In [4]:
b=np.array([4,5,6])

In [5]:
np.stack([a,b],axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
np.stack((a,b),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
np.stack(([1,2,3],[4,5,6]),axis=1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [10]:
c = [ [1,2,3],[4,5,6]]
np.stack(c,axis=0)

array([[1, 2, 3],
       [4, 5, 6]])