### shape(R,)和shape(R,1)的区别
可以参考[这个文章](https://stackoverflow.com/questions/22053050/difference-between-numpy-array-shape-r-1-and-r)
将1维向量二维化,首先要清楚它column还是row,添加一个None的维度即可完成转化.
```python
    column = column[:,None];
    row = row[None,:]
```

### 切片

In [128]:
#切片是满足 左闭，右开
a=[1,2,3,4]
print(a[::1]);
print(a[::-1]);
print(a[:]);
print(a[:-1]);
print(a[:-2]);

[1, 2, 3, 4]
[4, 3, 2, 1]
[1, 2, 3, 4]
[1, 2, 3]
[1, 2]


### numpy行向量列向量之间转换

In [20]:
import numpy as np;
# np没有一维向量,只有(4)
a=np.array([1,2,3,4]);
print('a:',a,'a.shape',a.shape)

#转变成 (1,4)
aa=np.array([a])
print('aa:',aa,'aa.shape',aa.shape)

#转变成(4,1)
aa=np.array([a]).T
print('aa:\n',aa,'\naa.shape',aa.shape)

# 用reshape
b=a.reshape(-1,1);
print('row into column vec:\n',b,'\nb.shape',b.shape)
#列向量变行向量 reshape
c=b.reshape(1,-1);
print('column into row vec:',c,'c.shape',c.shape)

a: [1 2 3 4] a.shape (4,)
aa: [[1 2 3 4]] aa.shape (1, 4)
aa:
 [[1]
 [2]
 [3]
 [4]] 
aa.shape (4, 1)
row into column vec:
 [[1]
 [2]
 [3]
 [4]] 
b.shape (4, 1)
column into row vec: [[1 2 3 4]] c.shape (1, 4)


### 倒序循环

In [26]:
for i in range(10-1,-1,-1):
    print(i);

9
8
7
6
5
4
3
2
1
0


###  行，列，全体求和

In [28]:
A=np.ones([3,3]);
np.sum(A)

9.0

In [30]:
np.sum(A[:,1])

3.0

In [134]:
np.sum(A[1,:])

26

In [138]:
A=np.array([[1,2,3,4],[5,6,7,8]]);
print('A=\n',A);

#然后对A的每一列除以sum的值 ，相当于列的概率分布
# none的作用还是初始化1维向量
Sum = np.sum(A,axis=0)
print('Sum row together\n',Sum);
print('Sum[None,:]\n',Sum[None,:])
print('Sum[None,:] shape\n',Sum[None,:].shape)
print('Matrix divide row-vector:\n', A / Sum[None,:]);


Sum=np.sum(A,axis=1);
print('Sum column together\n',Sum);
print('Matrix divide column-vector:\n',A / Sum[:,None]);

A=
 [[1 2 3 4]
 [5 6 7 8]]
Sum row together
 [ 6  8 10 12]
Sum[None,:]
 [[ 6  8 10 12]]
Sum[None,:] shape
 (1, 4)
Matrix divide row-vector:
 [[ 0.16666667  0.25        0.3         0.33333333]
 [ 0.83333333  0.75        0.7         0.66666667]]
Sum column together
 [10 26]
Matrix divide column-vector:
 [[ 0.1         0.2         0.3         0.4       ]
 [ 0.19230769  0.23076923  0.26923077  0.30769231]]


### 最后一个元素用a[-1]来寻找 ,类似matlab a(end)

In [33]:
a1=np.array([1,2,3])
a1[-1]

3

In [35]:
a1[-2]

2

In [62]:
a1[-3]

1

In [63]:
a1[::-1]

array([3, 2, 1])

### 矩阵连续点乘

In [58]:
size = [3,3]
A=np.random.rand(3,3);
B= A+1;
C =A /2 ;
D = A -10;

ans=A.dot(B).dot(C).dot(D)
print(ans)
print('------')
from functools import reduce ;
ans = reduce(np.dot,[A,B,C,D]);
print(ans)


[[-65.33427095 -67.19555078 -68.65499209]
 [-36.19156642 -37.189905   -38.01345919]
 [-64.37481746 -66.18932156 -67.63437653]]
------


array([[-65.33427095, -67.19555078, -68.65499209],
       [-36.19156642, -37.189905  , -38.01345919],
       [-64.37481746, -66.18932156, -67.63437653]])

### 矩阵的多维性质

In [116]:
A=np.random.randint(1,10,[3,3,3],dtype=np.int64)
A

array([[[6, 4, 9],
        [4, 9, 5],
        [8, 6, 4]],

       [[3, 8, 7],
        [6, 6, 4],
        [1, 2, 3]],

       [[6, 5, 5],
        [4, 6, 6],
        [9, 4, 2]]])

In [117]:
np.sum(A,axis=0)

array([[15, 17, 21],
       [14, 21, 15],
       [18, 12,  9]])

In [118]:
#沿axis同于1的方向做加法 等价于3x3中的行的方向
np.sum(A,axis=1)

array([[18, 19, 18],
       [10, 16, 14],
       [19, 15, 13]])

In [109]:
np.sum(A,axis=2)

array([[27, 12, 16],
       [17, 15,  9],
       [14, 10, 10]])

In [110]:
# 所有3x3的[0,0]位置组成新的向量
A[:,0,0]

array([9, 8, 9])

In [111]:
# 第1个的 3x3（从第0个开始）
A[1,]
#等价A[1,:,:], 后面如果有冒号，可以省略

array([[8, 3, 6],
       [2, 4, 9],
       [2, 2, 5]])

In [112]:
A[:,1,:]
# 从后面开始，后面两个维度[1,:]代表3x3矩阵的第1行，再往前看:,代表所有3x3矩阵的第1行

array([[4, 6, 2],
       [2, 4, 9],
       [4, 1, 5]])

### empty初始化

In [114]:
A=np.empty(A.shape);
print(A)

[[[ 0.16933267  0.79862806  0.25106778]
  [ 0.76589056  0.91035973  0.16881393]
  [ 0.84442154  0.62991591  0.45926804]]

 [[ 0.19458677  0.08658751  0.60264572]
  [ 0.55967403  0.07950939  0.62167819]
  [ 0.32808307  0.26253843  0.99294713]]

 [[ 0.19907042  0.38073091  0.63410862]
  [ 0.20123251  0.73627526  0.5749341 ]
  [ 0.42085077  0.39527889  0.90448883]]]


In [140]:
np.random.randn(2,2)

array([[ 1.72514035,  0.32715656],
       [ 2.16896929, -0.99099336]])

### 判断矩阵的每一行，与另外一个向量是否相等，得到真值矩阵

In [148]:
A=np.array([[0,0,0,0],[1,1,1,1],[2,2,2,2]]);
vec = np.array([0,2,1,2]);
np.where(A ==vec,1,0)

array([[1, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 1, 0, 1]])

### tile用法

In [155]:
b = np.tile(np.array([1,2,3]),);
b

array([1, 2, 3])